# Generated by Django 2.2 on 2020-02-11 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estoque_app.Produto')),
                ('estoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque_app.Produto')),
            ],
        ),
    ]
